### ISSUE TITLE
Stopped working with kernel 5.8+ on Arch Linux

### ISSUE THREAD

**Issue by clue44** [aircrack-ng/rtl8812au#712]
The latest working version was 5.7.9 for this code. Something changed in kernel 5.8 and the driver now fails to compile against the 5.8+ headers.

==> dkms install --no-depmod -m rtl88xxau -v r1068.df2b8df -k 5.8.5-zen1-1-zen
Error! Bad return status for module build on kernel: 5.8.5-zen1-1-zen (x86_64)
Consult /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/make.log for more information.

```
DKMS make.log for rtl88xxau-r1068.df2b8df for kernel 5.8.5-zen1-1-zen (x86_64)
Sat Aug 29 07:34:52 PM CEST 2020
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.5-zen1-1-zen/build M=/var/lib/dkms/rtl88xxau/r1068.df2b8df/build  modules
make[1]: Entering directory '/usr/lib/modules/5.8.5-zen1-1-zen/build'
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_set.o
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_io.c:47:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_io.c:47:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_query.c:17:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_query.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_set.c:17:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_set.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_debug.c:17:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_debug.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:70,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_security.c:17:
/var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
  257 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service_linux.h:52,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/osdep_service.h:58,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_security.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_query.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_io.o] Error 1
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_ioctl_set.o] Error 1
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_security.o] Error 1
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_cmd.o] Error 1
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build/core/rtw_debug.o] Error 1
make[1]: *** [Makefile:1754: /var/lib/dkms/rtl88xxau/r1068.df2b8df/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.5-zen1-1-zen/build'
make: *** [Makefile:2245: modules] Error 2

```

**Comment by tomty89** [comment]
Update your code? https://github.com/aircrack-ng/rtl8812au/commit/e90626b5c3d2dec78f3177de8bf8e4e31d69c4ab

**Comment by clue44** [comment]
Thanks, worked fine. Appriciate the heads up :) 

-- 
  Christer Nissen
  nissen@fastmail.se

**Comment by diederikdehaas** [comment]
Sounds to me the issue can thus be closed.

**Comment by kimocoder** [comment]
This issue is resolved.
