### ISSUE TITLE
Failed to build on Linux kernel version 6.16.8+kali-amd64.

### ISSUE THREAD

**Issue by jeroldcamacho** [aircrack-ng/rtl8812au#1245]
```
╰─➤  make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.16.8+kali-amd64/build M=/home/mirai/Desktop/alfa/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-6.16.8+kali-amd64'
make[2]: Entering directory '/home/mirai/Desktop/alfa/rtl8812au'
  CC [M]  core/rtw_cmd.o
core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.16.8+kali-common/scripts/Makefile.build:292: core/rtw_cmd.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:2027: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/home/mirai/Desktop/alfa/rtl8812au'
make[1]: *** [/usr/src/linux-headers-6.16.8+kali-common/Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.16.8+kali-amd64'
make: *** [Makefile:1730: modules] Error 2

╰─➤  uname -r                                                                                                                                                                        2 ↵
6.16.8+kali-amd64
```

**Comment by josinaldobarbosa** [comment]
[giuliobenetti](https://github.com/giuliobenetti) Can you help with this? I already tried with the [fix/linux-6.16](https://github.com/aircrack-ng/rtl8812au/pull/1236)

**Comment by ziyaniftaliev** [comment]
Hi, man. I can't do it either!

**Comment by meir-rozen** [comment]
There is a solution to the problem.

**Comment by LU5GOON** [comment]
The last build supported was for Linux Kernel version 6.13 and has not been updated since. Anything above that is not supported and will fail like what you are experiencing here.

**Comment by meir-rozen** [comment]
I installed it now on 6.13 and it worked thanks for the help
