### ISSUE TITLE
-Werror=array-bounds

### ISSUE THREAD

**Issue by rasdark** [aircrack-ng/rtl8812au#1017]
Hi.
I'm trying to build on Gentoo with kernel 6.0.7 and get the following error
```
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c: In function ‘rtw_mi_p2p_chk_state’:
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c:1255:24: error: array subscript ‘enum P2P_STATE[0]’ is partly outside array bound
s of ‘u8[1]’ {aka ‘unsigned char[1]’} [-Werror=array-bounds]
1255 |         enum P2P_STATE state = *(enum P2P_STATE *)data;
|                        ^~~~~
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c:1261:12: note: while referencing ‘in_data’
1261 |         u8 in_data = p2p_state;
|            ^~~~~~~
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c: In function ‘rtw_mi_buddy_p2p_chk_state’:
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c:1255:24: error: array subscript ‘enum P2P_STATE[0]’ is partly outside array bound
s of ‘u8[1]’ {aka ‘unsigned char[1]’} [-Werror=array-bounds]
1255 |         enum P2P_STATE state = *(enum P2P_STATE *)data;
|                        ^~~~~
/tmp/portage/net-wireless/rtl8812au-20221105/work/rtl8812au-afd38cc6841dfcc9cd7198c5daf30926cfc2eb68/core/rtw_mi.c:1267:12: note: while referencing ‘in_data’
1267 |         u8 in_data  = p2p_state;
|            ^~~~~~~
```

**Comment by kimocoder** [comment]
This issue should be fixed now
