### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by mehmetyldz87** [aircrack-ng/rtl8812au#438]
Hi, 

When I try to compile and install driver. I encounter with this error.  What is this error ? How can I fix it? Thanks for your helps

OS: Ubuntu 16.04 LTS

/home/gorkes/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_sta_assoc’:
/home/gorkes/rtl8812au/os_dep/linux/ioctl_cfg80211.c:4484:3: error: implicit declaration of function ‘cfg80211_sinfo_alloc_tid_stats’ [-Werror=implicit-function-declaration]
   cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
   ^
/home/gorkes/rtl8812au/os_dep/linux/ioctl_cfg80211.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-misleading-indentation’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
cc1: some warnings being treated as errors
scripts/Makefile.build:330: recipe for target '/home/gorkes/rtl8812au/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/home/gorkes/rtl8812au/os_dep/linux/ioctl_cfg80211.o] Error 1
Makefile:1571: recipe for target '_module_/home/gorkes/rtl8812au' failed
make[1]: *** [_module_/home/gorkes/rtl8812au] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-65-generic'
Makefile:1608: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by mehmetyldz87** [comment]
when I try "sudo ./dkms-install.sh" method. This error message is given. 

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
'make' -j4 KVER=4.15.0-65-generic KSRC=/lib/modules/4.15.0-65-generic/build..........(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8812au: 5.6.4.1 not found
Error! Bad return status for module build on kernel: 4.15.0-65-generic (x86_64)
Consult /var/lib/dkms/rtl8812au/5.6.4.1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
'make' -j4 KVER=4.15.0-65-generic KSRC=/lib/modules/4.15.0-65-generic/build..........(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8812au: 5.6.4.1 not found
Error! Bad return status for module build on kernel: 4.15.0-65-generic (x86_64)
Consult /var/lib/dkms/rtl8812au/5.6.4.1/build/make.log for more information.
Finished running dkms install steps.

**Comment by kimocoder** [comment]
Yes I think I know where to look, I will do some tests soon. I'll leave a note here soon

**Comment by lupa18** [comment]
Hello ! here same problem :pray:

**Comment by mehmetyldz87** [comment]
hi @kimocoder  ,did you get a chance to look at the problem? Thanks

**Comment by ghost** [comment]
Hello sir,am at Ubuntu 18.04.3 LTS and having the same issue.!

**Comment by kimocoder** [comment]
@mehmetyldz87 @Trivedi-dot @lupa18 

Done lots of changes. Update to v5.6.4.2, clone it and compile/build/install/reboot and see if the problem is fixed, report back if it's resolved or the problem is persistent :+1:

**Comment by lupa18** [comment]
it seem is working with dkms. thanks!

**Comment by kimocoder** [comment]
Awesome! Another issue smashed.

If you'd encounter more issues, please open tickets and share details :1st_place_medal:

**Comment by mehmetyldz87** [comment]
Thanks , problem solved for me
