### PR TITLE
rtl8812au: Fix builds with kernel 5.18

### PR DESCRIPTION
**Pull request by heitbaum**
Error during compile of kernel 5.18 with
- https://github.com/LibreELEC/LibreELEC.tv/pull/6423

```
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-ld: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic.x86_64-11.0-devel/build/RTL8192DU-eb09a4e6e96a5a033afe60c71022bfa42eea148a/core/rtw_security.o: in function `is_multicast_mac_addr':
rtw_security.c:(.text+0x23e0): multiple definition of `is_multicast_mac_addr'; /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic.x86_64-11.0-devel/build/RTL8192DU-eb09a4e6e96a5a033afe60c71022bfa42eea148a/core/rtw_cmd.o:rtw_cmd.c:(.text+0x2c): first defined here
```

- Issue: https://github.com/lwfinger/rtl8192du/issues/91
- Fixed at: https://github.com/lwfinger/rtl8192du/commit/a4e32040416d2dba2611a8f410a4f7663a425eb3

reading
- https://lore.kernel.org/lkml/20190116132010.31395-1-natechancellor@gmail.com/

### CODE REVIEW

**Comment by heitbaum** [comment]
@kimocoder / cc: @CGarces 
- if ok, can this please be pulled. Thanks.

**Comment by CGarces** [comment]
CI fails due dependency with GCC 11.2.0 (I'm waiting for 11.2 version at ubuntu-toolchain-r/test)

 But the patch looks ok and is ready to merge, (also #961).

**Comment by margual56** [comment]
Hi! Sorry to bother 😅 

I have just updated to kernel 5.18, and since the main branch does not work, I was trying to compile this pull request and...

```C
rtl8812au/os_dep/osdep_service.c:1295:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1295 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~

rtl8812au/os_dep/linux/rtw_proc.c:216:34: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
  216 |         ssize_t index = (ssize_t)PDE_DATA(inode);
      |                                  ^~~~~~~~
      |                                  NODE_DATA

cc1: some warnings being treated as errors
```
(Build command: `make -j16 KVER=5.18.0-zen1-1-zen KSRC=/lib/modules/5.18.0-zen1-1-zen/build`), and it worked just fine on kernels 5.14 to 5.17.

I hope this helps! 

# Hardware
WiFi adapter: TP-Link Archer T2U PLUS [RTL8821AU]
Kernel: 5.18.0-zen1-1-zen
OS: Arch Linux x86_64
GCC version: gcc version 12.1.0

**Comment by yusi1** [comment]
patch worked perfectly for me, could compile on kernel 5.18, please merge

**Comment by kimocoder** [comment]
I added kernel v5.18 support, but thanks for providing :1st_place_medal:
