### ISSUE TITLE
Fails to compile on Debian 13 Testing with kernel 6.16.12+deb14+1-amd64

### ISSUE THREAD

**Issue by AndrzejL-eu** [aircrack-ng/rtl8812au#1240]
root@Tpad-X201:~# sudo apt -y install bc build-essential dkms linux-headers-amd64 git
root@Tpad-X201:~# git clone https://github.com/aircrack-ng/rtl8812au.git
root@Tpad-X201:~# cd /opt/rtl8812au/
root@Tpad-X201:/opt/rtl8812au# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.16.12+deb14+1-amd64/build M=/opt/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-6.16.12+deb14+1-amd64'
make[2]: Entering directory '/opt/rtl8812au'
  CC [M]  core/rtw_cmd.o
core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.16.12+deb14+1-common/scripts/Makefile.build:292: core/rtw_cmd.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.16.12+deb14+1-common/Makefile:2027: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.16.12+deb14+1-common/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/opt/rtl8812au'
make[1]: *** [/usr/src/linux-headers-6.16.12+deb14+1-common/Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.16.12+deb14+1-amd64'
make: *** [Makefile:1730: modules] Error 2
root@Tpad-X201:/opt/rtl8812au# uname -a
Linux Tpad-X201 6.16.12+deb14+1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.16.12-2 (2025-10-16) x86_64 GNU/Linux
root@Tpad-X201:/opt/rtl8812au# sudo make dkms_install
mkdir: created directory '/usr/src/8812au-5.6.4.2_35491.20191025'
cp -r * /usr/src/8812au-5.6.4.2_35491.20191025
dkms add -m 8812au -v 5.6.4.2_35491.20191025
Creating symlink /var/lib/dkms/8812au/5.6.4.2_35491.20191025/source -> /usr/src/8812au-5.6.4.2_35491.20191025
dkms build -m 8812au -v 5.6.4.2_35491.20191025
Sign command: /lib/modules/6.16.12+deb14+1-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...

Building module(s)...(bad exit status: 2)
Failed command:
'make' -j4 KVER=6.16.12+deb14+1-amd64 KSRC=/lib/modules/6.16.12+deb14+1-amd64/build

Error! Bad return status for module build on kernel: 6.16.12+deb14+1-amd64 (x86_64)
Consult /var/lib/dkms/8812au/5.6.4.2_35491.20191025/build/make.log for more information.
make: *** [Makefile:1790: dkms_install] Error 10
root@Tpad-X201:/opt/rtl8812au#
