### ISSUE TITLE
Fix compilation issue kernels < 4.18 (Ubuntu 18.04 and derived distros) 

### ISSUE THREAD

**Issue by af778998** [aircrack-ng/rtl8812au#676]
Hello,
looks like there is a regression, (https://github.com/aircrack-ng/rtl8812au/pull/420)

commit 9ec3a13fc80cb20e49e461348ef2a68c63f3b48e (HEAD -> v5.6.4.2, origin/v5.6.4.2, origin/HEAD)

does not compile on Ubuntu 18.04:
aircrack-rtl8812au/os_dep/linux/ioctl_cfg80211.c:4449:3: error: implicit declaration of function ‘cfg80211_sinfo_alloc_tid_stats’; did you mean ‘cfg80211_inform_bss_width’? [-Werror=implicit-function-declaration]
   cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cfg80211_inform_bss_width

probably caused from 

commit e65b190ab79dc278a390cd5fcfc6a2f64318561d

diff --git a/os_dep/linux/ioctl_cfg80211.c b/os_dep/linux/ioctl_cfg80211.c
index e702202..62bcbd5 100644
--- a/os_dep/linux/ioctl_cfg80211.c
+++ b/os_dep/linux/ioctl_cfg80211.c
@@ -4448,6 +4448,7 @@ void rtw_cfg80211_indicate_sta_assoc(_adapter *padapter, u8 *pmgmt_frame, uint f
                sinfo.filled = STATION_INFO_ASSOC_REQ_IES;
                sinfo.assoc_req_ies = pmgmt_frame + WLAN_HDR_A3_LEN + ie_offset;
                sinfo.assoc_req_ies_len = frame_len - WLAN_HDR_A3_LEN - ie_offset;
`+               cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);`
                cfg80211_new_sta(ndev, get_addr2_ptr(pmgmt_frame), &sinfo, GFP_ATOMIC);
        }
 #else /* defined(RTW_USE_CFG80211_STA_EVENT) */

at least the Fix  from #420 

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 18, 0))
		cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
#endif

helped it to compile

**Comment by kimocoder** [comment]
Issue should be resolved. Re-open if not.
