### ISSUE TITLE
Drivers failing to compile with Kernel 6.5 - fix

### ISSUE THREAD

**Issue by github-johnny** [aircrack-ng/rtl8812au#1109]
Hello there.

Been working on making the drivers build on Linux kernel 6.5.  The attached 6_5.patch allows this to happen.

This patch was created by following changes in:
https://github.com/aircrack-ng/rtl8812au/pull/1008/files
https://github.com/aircrack-ng/rtl8812au/pull/992/files
https://github.com/aircrack-ng/rtl8812au/pull/961

As well as updating a few lines for "too few arguments to function".  Hopefully someone can double check this, not 100% I did it right - even though it's working.

I'm not a github user, figuring out the forking still.  I made a patch to move things along and will figure out the pull request stuff in the future.  To use the patch, download the 6_5.patch, unzip the rtl8812au-5.6.4.2 drivers.

Patch sha256 hash is:
7c484c306886d70b6f911746ff8527282254653217cb73e84d4ff1e8c0f2feec

Copy the patch into the rtl8812au-5.6.4.2 directory.

$patch -p1 -b < 6_5.patch
$sudo make dkms_install

If you're using Secureboot, the modules aren't signed automatically in Ubuntu 22.04 with this kernel. If running this OS, the .ko.zst can be decompressed, then sign the .ko, and recompress.

For example, with kernel 6.5.0-1003-oem:

$modinfo 88XXau
*output will indicate none of the following fields:
sig_id
signer
sig_key
sig_hashalgo
signature

$sudo zstd -d /lib/modules/6.5.0-1003-oem/updates/dkms/88XXau.ko.zst
$sudo kmodsign sha512 /path/to/mok.priv /path/to/mok.der /lib/modules/6.5.0-1003-oem/updates/dkms/88XXau.ko
$sudo rm /lib/modules/6.5.0-1003-oem/updates/dkms/88XXau.ko.zst
$sudo zstd /lib/modules/6.5.0-1003-oem/updates/dkms/88XXau.ko
$sudo rm /lib/modules/6.5.0-1003-oem/updates/dkms/88XXau.ko

$modinfo 88XXau
*output should now include the following fields:
sig_id
signer
sig_key
sig_hashalgo
signature

$modprobe 88XXau
^- should now work.

I'm sure there's a more elegant / correct way to handle secureboot, but this is what I've worked out so far.
[6_5.patch.gz](https://github.com/aircrack-ng/rtl8812au/files/12734820/6_5.patch.gz)

Thank you for your time.

**Comment by github-johnny** [comment]
Guess I was working off of old files.  Working on the pull request I found the issue is resolved already.  My apologies for wasting time with this non-issue.

**Comment by github-johnny** [comment]
Guess I was working off of old files.  While working on the pull request, it looks like the issue is already resolved.  My apologies for wasting time on this non-issue.
